# Generated by Django 4.0.6 on 2022-07-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('Trimestral', 'Trimestral'), ('Anual', 'Anual')], max_length=100)),
                ('nivel', models.CharField(choices=[('Chefia', 'Chefia'), ('Colega', 'Colega'), ('Própria', 'Própria')], max_length=255)),
                ('media', models.CharField(max_length=100, null=True)),
                ('periodo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_ingresso', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=100)),
                ('depto', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('avaliavel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('1. Assiduidade Pontualidade', '1. Assiduidade Pontualidade'), ('2. Disciplina', '2. Disciplina'), ('3. Capacidade de Iniciativa', '3. Capacidade de Iniciativa'), ('4. Produtividade', '4. Produtividade'), ('5. Responsabilidade', '5. Responsabilidade')], max_length=100)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterio_avaliacao', to='avaliacao.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Chefe', 'Chefe'), ('Colega', 'Colega'), ('Próprio', 'Próprio')], max_length=100)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_avaliadores', to='avaliacao.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliador', to='avaliacao.avaliador'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='avaliacao.funcionario'),
        ),
    ]
